### ISSUE TITLE
Custom build steps

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#15]
No idea yet how to tackle this. Useful and required for:
- Building extensions
- Publishing pipelines

**Comment by synixebrett** [comment]
What do you think about changing #9 to be a utility? We could implement build steps as run utilities or external programs either prebuild or postbuild. Using zip as part of the build process will force people wanting to include extensions to use `--no-zip`, add their extensions, then zip manually. We could do something like
```json
{
  ...
  "prebuild": [
    "minify-sqf",
  ],
  "postbuild": [
    "cmake CMakeLists.txt",
    "make",
    "@zip"
  ]
}
```
I think using `@` to indicate a HEMTT utility *should* be fine.
This will allow a high level of customisation, while still providing a low barrier of entry if we have a few common examples in the documentation. It will also keep the number of build flags down, as adding a handful of utilities is cleaner than a handful of build flags.

Another advance is not having to use a large `hemtt build` command with a bunch of flags, but instead just using `hemtt build`. This will make it easier for people just getting into contributing to ACE, CBA, etc easier since they won't *need* to know what build flags to use.

**Comment by jonpas** [comment]
I like this a lot!
