### ISSUE TITLE
Configurable Optionals

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#65]
`addons` is static anyways, as Arma 3 requires that.

However, `optionals` is completely custom, we could easily allow custom name for it and even allow more than 1 optionals folder.

**Comment by synixebrett** [comment]
In my opinion, `optionals` has become a defacto standard that we can rely on / enforce. I would rather see customization for optionals through the HEMTT project file.

**Comment by jonpas** [comment]
Project file is what I was going for.

I agree, just thought of it as some people might have a different name.

**Comment by synixebrett** [comment]
we could try getting `compats` going, with `optionals` for additional functionality and `compats` for compatibility mods

**Comment by jonpas** [comment]
But that is exactly why I would make it configurable and allow array input for the configuration. We don't have to care about how people split them then.

**Comment by synixebrett** [comment]
While I generally agree that as much as possible should be configurable, I think we should have `addons`, `optionals`, and `compats` as 3 "supported" folders, and projects like ACE can then choose to move their compats and have it be fully supported and functional.

In addition to that, there is no reason we can't have a configurable array of folders, that simply get built during `hemtt build`. The HEMTT CLI should only support `--opts cool_feature --compats yawm`. Otherwise, it would become cluttered with flags to specify which addon from which folder.

**Comment by jonpas** [comment]
Agreed.

**Comment by synixebrett** [comment]
What are your thoughts on this? I'm kinda thinking of closing this. The first party support for `optionals` and `compats` seems good enough in my opinion. I can't see any reason why someone would have addons outside of those.

**Comment by jonpas** [comment]
I think it's fine as it is. I still don't really like enforcing separation into `optionals` and `compats due to their nature, but that can be solved with #197.
